---
- name: Installe Apticron
  become: true
  apt:
    name: apticron
    state: present
    update_cache: yes

- name: Initialise la Configuration
  become: true
  template:
    src: apticron.conf.j2
    dest: /etc/apticron/apticron.conf
    owner: root
    group: root
    mode: 0644
