---
- name: Installe les logiciels de base
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - acl
    - vim
    - tmux

- include: "timesyncd.yml"
- include: "users.yml"
- include: "smtp.yml"
- include: "apticron.yml"
- include: "fail2ban.yml"
