---
- name: Supprimer les anciennes version de docker
  become: true
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
    autoremove: yes
  with_items:
    - docker-engine
    - docker.io
    - docker-engine
    - containerd
    - runc

- name: Ajoute sur le support de https pour apt et les certificats nécessaires.
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name: Ajoute la clé du dépôt docker
  become: true
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: Ajoute le dépôt docker
  become: true
  apt_repository:
    filename: 'docker'
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    update_cache: yes

- name: Installe Docker
  become: true
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: Ajoute l'utilisateur bredow au groupe docker
  become: true
  user: name=bredow groups=docker append=yes

- name: Ajoute l'utilisateur amaraniha au groupe docker
  become: true
  user: name=amraniha groups=docker append=yes

- name: Lance le service docker
  become: true
  service:
    name: docker
    enabled: yes
    state: started
