- hosts: docker
  become: yes
  become_method: sudo
  tasks:
    - name: Supprimer les anciennes version de docker
      apt:
        name: docker-engine
        state: absent
        update_cache: yes
        autoremove: yes
 
    - name: Ajoute sur le support de https pour apt et les certificats nécessaires.
      apt: 
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - software-properties-common

    - name: Ajoute la clé du dépôt docker
      apt_key: 
        url: "https://download.docker.com/linux/debian/gpg" 
        state: present

    - name: Ajoute le dépôt docker 
      apt_repository: 
        filename: 'docker'    
        repo: deb [arch=amd64] https://download.docker.com/linux/debian jessie stable
        update_cache: yes 

    - name: Installe Docker
      apt: 
        name: docker-ce 
        state: present 
        update_cache: yes

    - name: Ajoute l'utilisateur bredow au groupe docker
      user: name=bredow groups=docker append=yes

    - name: Lance le service docker
      service: 
        name: docker
        enabled: yes 
        state: started

    - name : Installe pip
      easy_install:
        name: pip
        state: latest

    - name: Installe docker-compose
      pip: 
        name: docker-compose 
        state: latest



